version: '2'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}
    environment:
      - PORT=${PORT}
      - API_PORT=${API_PORT}
      - REVERSE_PROXY_PORT=${REVERSE_PROXY_PORT}
